import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import LandingBar from "@/components/LandingNav";
import PaginationClient from "@/components/PaginationClient";
import { AspectRatio } from "@/components/ui/aspect-ratio";
import LoggedNav from "@/components/LoggedNavBar";
import PagHyper from "@/components/PaginationHyper";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* Background full-screen fixed */}
        <div className="fixed inset-0 -z-10 w-full h-full">
          <AspectRatio ratio={16 / 9} className="w-screen h-screen">
            <Image
              src="https://assets.nflxext.com/ffe/siteui/vlv3/03ad76d1-e184-4d99-ae7d-708672fa1ac2/web/BR-pt-20241111-TRIFECTA-perspective_1b6d896f-f960-4456-8070-9d4b4a68946d_large.jpg"
              alt="Background Image"
              layout="fill"
              className="object-cover"
            />
          </AspectRatio>
        </div>

        {/* Navbar and content */}
        <div className="relative z-10">
          
          {children}
          
        </div>
      </body>
    </html>
  );
}